version: '3.7'

services:
  rabbitmq:
    container_name: automanet-eventbus-rabbitmq
    image: rabbitmq:3.11-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - '5672:5672'
      - '15672:15672'

  php:
    container_name: automanet-eventbus-app
    tty: true
    depends_on:
      - rabbitmq
    build:
        context: .
    volumes:
      - './:/app'